ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{ env }}".gaddam.online
REDIS_HOST: redis-"{{ env }}".gaddam.online
USER_HOST: user-"{{ env }}".gaddam.online
CATALOGUE_HOST: catalogue-"{{ env }}".gaddam.online
CART_HOST: cart-"{{ env }}".gaddam.online
MYSQL_HOST: mysql-"{{ env }}".gaddam.online
SHIPPING_HOST: shipping-"{{ env }}".gaddam.online
PAYMENT_HOST: payment-dev.gaddam.online
RABBITMQ_HOST: rabbitmq-dev.gaddam.online