[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.gaddam.online

[redis]
redis-dev.gaddam.online

[user]
user-dev.gaddam.online

[cart]
cart-dev.gaddam.online

[mysql]
mysql-dev.gaddam.online

[shipping]
shipping-dev.gaddam.online

[rabbitmq]
rabbitmq-dev.gaddam.online

[payment]
payment-dev.gaddam.online

[frontend]
frontend-dev.gaddam.online